common: &common
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *common
  database: development_db

test:
  <<: *common
  database: test_db

production:
  <<: *common
  database: production_db

staging:
  <<: *common
  database: staging_db
